// <auto-generated />
using System;
using Laplap.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LapLap.ApiService.Migrations
{
    [DbContext(typeof(RequestContext))]
    [Migration("20251129141026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Laplap.ApiService.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aggression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Care")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Care_Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dog_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fears")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gives_Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("How_To_Get_To_You")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("How_You_Found_Out")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nuances")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picks_Things_Up")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pulls_The_Leach")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time_Of_Call")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Traumas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Walk_Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("What_Is_There")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Your_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
